version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ee
    restart: always
    hostname: 192.168.2.118
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.2.118'
        gitlab_rails['initial_root_password']='12345678'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'

  gitlab-runner:
    image: gitlab/gitlab-runner
    restart: always
    ports:
      - '8093:8093'
